Adds support for environment variable configuration
paketo-buildpacks/go-build pull request #109
Opened 2020-12-18 22:46 UTC by ForestEckhardt

- Separates buildpack.yml parsing into its own structure to aide in
business logic when it comes to deprecating buildpack.yml

Please confirm the following:
* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have added an integration test, if necessary.

2020-12-18 22:49 UTC, ForestEckhardt commented
TODO LIST:
* [ ] Figure out failing test cases.
* [ ] Add integration testing around environment variables having higher priority.
* [ ] Add logging for if a user is trying to configure the buildpack using environment variable.
* [ ] Write up documentation for the website as well as the README.

2021-01-12 22:59 UTC, wburningham commented
Will using the `BP_GO_*` ENV variables clear the layers cache or will it suffer from the same issues reported in #88 and #89?

2021-01-13 16:15 UTC, ForestEckhardt commented
@wburningham It will currently have those same issue but that is the next set of work we are looking onto around making sure that we rebuild the layers at an appropriate time.

2021-01-13 18:08 UTC, ryanmoran requested changes

2021-01-13 20:52 UTC, ryanmoran requested changes

2021-01-13 20:52 UTC, ryanmoran commented on go.mod
> +	github.com/hashicorp/hcl v1.0.0
```suggestion
```

2021-01-15 17:18 UTC, ryanmoran approved these changes

2021-01-15 17:21 UTC, merged