Use workspace modules with `BP_GO_WORK_USE`
paketo-buildpacks/go-build pull request #537
Opened 2023-12-15 09:31 UTC by mamachanko

## 🚧 TODO 
* [ ] green unit & integration tests
* [ ] PR description

---

## Summary

## Use Cases

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2023-12-15 11:07 UTC, mamachanko commented
@robdimsdale @ForestEckhardt Unfortunately, I couldn't figure out how to run integration tests locally. Reverse engineering the `.github/workflows/test-pull-request.yml` wasn't successful either since I couldn't figure out which `--builder` to pass to `./scripts/integration.sh`. I was hoping this PR would do that for me, but a semver label is missing.

2024-01-23 15:59 UTC, ForestEckhardt requested changes
Hey there! This PR look great. My only call out is that I would like to see some unit test for the new functionality that you added. I would be more than happy to consult with you on adding those or back filling them and letting you take a look. Just let me know!

2024-01-23 16:07 UTC, mamachanko commented
> My only call out is that I would like to see some unit test for the new functionality that you added.

I shall happily add unit tests! 

Until then, would you be able to instruct me on how to run the integration locally?

2024-01-28 15:24 UTC, mamachanko commented on go_build_process_test.go
> +				"      Completed in 0s",
🤔 It's consistently expecting `0s` while other tests want `1s`. I can't quite tell why.

2024-02-02 13:39 UTC, mamachanko commented
> It looks like all of the integration tests are failing at the moment. Could you take a look in that?

Done. Finally I figured out how to run the integration tests for a builder locally with:

```sh
./scripts/integration.sh --builder paketobuildpacks/builder-jammy-buildpackless-tiny --token "$GIT_TOKEN"
```

I understand that it runs across a matrix of `--builder` on CI, but I hope that tiny was a good-enough approximation locally.

Also, thanks to https://github.com/ForestEckhardt/freezer/issues/10 I was able to figure out how to rescue myself from `"failed to open cacheManager: EOF"` with `rm -rf $HOME/.freezer-cache`.

All that being said,

```sh
./scripts/unit.sh
./scripts/integration.sh --builder paketobuildpacks/builder-jammy-buildpackless-tiny --token "$GIT_TOKEN"
```

passes for me.

2024-02-06 21:38 UTC, ForestEckhardt commented
I think that this look great!

2024-02-06 21:39 UTC, ForestEckhardt approved these changes

2024-02-06 21:39 UTC, merged