Add logic to add paths under `cmd` to targets list
paketo-buildpacks/go-build pull request #79
Opened 2020-10-30 19:57 UTC by ForestEckhardt

2020-11-06 16:43 UTC, ryanmoran requested changes

2020-11-06 16:43 UTC, ryanmoran commented on build.go
> +			configuration := BuildConfiguration{}
If you aren't going to initialize the struct with field values, then you should just use a `var` declaration. Its a bit more idiomatic.
```suggestion
			var configuration BuildConfiguration
```

2020-11-06 16:43 UTC, ryanmoran commented on go.mod
> +	github.com/hashicorp/hcl v1.0.0
I think this got pulled in here by accident. Try running `go mod tidy`.

2020-11-06 17:00 UTC, ForestEckhardt commented
@ryanmoran That should resolve everything!

2020-11-07 00:20 UTC, ryanmoran approved these changes

2020-11-07 00:21 UTC, merged